In [1]:
from pathlib import Path

import pandas as pd
import polars as pl
import tensorflow as tf
import tensorflow_io as tfio
from sklearn.model_selection import train_test_split

2023-07-08 14:39:50.261897: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-07-08 14:39:52.568080: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-07-08 14:39:52.569406: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-08 14:39:57.313171: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


KeyboardInterrupt: 

In [ ]:
home =Path().cwd()
data_file = Path(home,'data/raw/raw_train.gzip') 
str(data_file)

'/workspaces/log_anomaly/data/raw/raw_train.gzip'

In [ ]:
df = pl.read_parquet(data_file)
print(len(df))
df.head()

4152659


shape: (5, 2)
┌───────────────────────────────────┬────────┐
│ Log                               ┆ Target │
│ ---                               ┆ ---    │
│ str                               ┆ str    │
╞═══════════════════════════════════╪════════╡
│  1117838570 2005.06.03 R02-M1-N0… ┆ normal │
│  1117838570 2005.06.03 R02-M1-N0… ┆ normal │
│  1117838570 2005.06.03 R02-M1-N0… ┆ normal │
│  1117838570 2005.06.03 R02-M1-N0… ┆ normal │
│  1117838570 2005.06.03 R02-M1-N0… ┆ normal │
└───────────────────────────────────┴────────┘

In [ ]:
np_file = df.to_numpy()

In [ ]:
numpy_ds = np_file[:100,:]
X = numpy_ds[:, 0]
Y = numpy_ds[:, 1]
Y[0]

'normal'

In [ ]:
dataset = tf.data.Dataset.from_tensor_slices((X, Y))

In [ ]:
for num in dataset.take(3):
    print(num)

(<tf.Tensor: shape=(), dtype=string, numpy=b' 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.50.363779 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n'>, <tf.Tensor: shape=(), dtype=string, numpy=b'normal'>)
(<tf.Tensor: shape=(), dtype=string, numpy=b' 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.50.527847 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n'>, <tf.Tensor: shape=(), dtype=string, numpy=b'normal'>)
(<tf.Tensor: shape=(), dtype=string, numpy=b' 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.50.675872 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected\n'>, <tf.Tensor: shape=(), dtype=string, numpy=b'normal'>)


2023-07-08 09:13:42.733672: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_1' with dtype string and shape [100]
	 [[{{node Placeholder/_1}}]]
